# Generated by Django 4.2.11 on 2026-01-30 03:51

import app.models.respuesta
import app.models.sesion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seccion', models.CharField(db_index=True, max_length=100)),
                ('valor', models.JSONField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('submenu', models.CharField(default='direct', max_length=50)),
                ('contenido', models.CharField(max_length=4000)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje_usuario', models.CharField(max_length=1000)),
                ('tipo_entrada', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=50)),
                ('respuesta_enviada', models.CharField(blank=True, max_length=4096, null=True)),
                ('timestamp_usuario', models.BigIntegerField()),
                ('timestamp_ms', models.BigIntegerField()),
                ('metadata_json', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_index=True, max_length=100)),
                ('contenido', models.CharField(max_length=4096)),
                ('siguientes_pasos', models.JSONField(default=app.models.respuesta.default_siguientes_pasos)),
                ('metadata_json', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('estado_actual', models.CharField(default='0', max_length=50)),
                ('historial_navegacion', models.JSONField(default=app.models.sesion.default_historial)),
                ('ultimo_mensaje', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp_ultimo_mensaje', models.BigIntegerField(blank=True, null=True)),
                ('inicio_sesion_ms', models.BigIntegerField()),
                ('ultimo_acceso_ms', models.BigIntegerField()),
                ('primer_acceso', models.BooleanField(default=True)),
                ('intentos_fallidos', models.BigIntegerField(default=0)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
    ]
