# Generated by Django 4.2.11 on 2026-01-30 04:21

import app.models.fields
import app.models.respuesta
import app.models.sesion
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='orden',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='config',
            name='valor',
            field=app.models.fields.LenientJSONField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='opciones',
            field=app.models.fields.LenientJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='metadata_json',
            field=app.models.fields.LenientJSONField(blank=True, db_column='metadata', null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='metadata_json',
            field=app.models.fields.LenientJSONField(blank=True, db_column='metadata', null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='siguientes_pasos',
            field=app.models.fields.LenientJSONField(default=app.models.respuesta.default_siguientes_pasos),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='datos_extra',
            field=app.models.fields.LenientJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='historial_navegacion',
            field=app.models.fields.LenientJSONField(default=app.models.sesion.default_historial),
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_items', to='app.menu')),
                ('target_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_padre', to='app.menu')),
                ('target_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_respuesta', to='app.respuesta')),
            ],
            options={
                'db_table': 'menu_opciones',
                'indexes': [models.Index(fields=['menu', 'orden'], name='menu_opcion_menu_id_46aee8_idx'), models.Index(fields=['menu', 'key'], name='menu_opcion_menu_id_75bc41_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='menuoption',
            constraint=models.UniqueConstraint(fields=('menu', 'key'), name='uniq_menu_key'),
        ),
    ]
