# Generated by Django 4.2.11 on 2026-01-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_orden_menu_parent_alter_config_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_contacto_ms', models.BigIntegerField()),
                ('ultimo_contacto_ms', models.BigIntegerField()),
                ('mensajes_totales', models.BigIntegerField(default=0)),
                ('ultimo_mensaje', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
