# Generated by Django 4.2.11 on 2026-01-30 05:15

import app.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(choices=[('in', 'entrante'), ('out', 'saliente'), ('system', 'sistema')], db_index=True, max_length=10)),
                ('tipo', models.CharField(db_index=True, default='text', max_length=50)),
                ('contenido', models.CharField(blank=True, max_length=4096, null=True)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp_ms', models.BigIntegerField(db_index=True)),
                ('metadata_json', app.models.fields.LenientJSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'mensajes',
            },
        ),
    ]
