# Generated by Django 4.2.11 on 2026-01-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_alias_waba_cliente_correo_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
