# Generated by Django 4.2.11 on 2026-01-30 05:31

import app.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='marketing_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CampanaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('idioma', models.CharField(default='es_AR', max_length=20)),
                ('cuerpo', models.TextField(blank=True)),
                ('variables_json', app.models.fields.LenientJSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campana_templates',
                'indexes': [models.Index(fields=['nombre', 'idioma'], name='campana_tem_nombre_eed262_idx')],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'whatsapp')], default='whatsapp', max_length=50)),
                ('tipo', models.CharField(choices=[('cumpleanos', 'cumpleanos'), ('manual', 'manual'), ('segmento', 'segmento')], default='cumpleanos', max_length=50)),
                ('direccion_offset', models.CharField(choices=[('antes', 'antes'), ('despues', 'despues'), ('mismo_dia', 'mismo_dia')], default='mismo_dia', max_length=20)),
                ('dias_offset', models.IntegerField(default=0)),
                ('hora_envio', models.TimeField(blank=True, null=True)),
                ('template_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('template_idioma', models.CharField(blank=True, max_length=20, null=True)),
                ('texto_estatico', models.TextField(blank=True)),
                ('variables_json', app.models.fields.LenientJSONField(blank=True, null=True)),
                ('segmento_json', app.models.fields.LenientJSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='app.campanatemplate')),
            ],
            options={
                'db_table': 'campanas',
            },
        ),
        migrations.CreateModel(
            name='CampanaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('programado', 'programado'), ('enviado', 'enviado'), ('fallido', 'fallido'), ('omitido', 'omitido')], default='programado', max_length=20)),
                ('programado_para', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500, null=True)),
                ('payload_json', app.models.fields.LenientJSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'db_table': 'campana_envios',
                'indexes': [models.Index(fields=['campana', 'estado'], name='campana_env_campana_5e5491_idx'), models.Index(fields=['cliente', 'estado'], name='campana_env_cliente_3ae355_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campanaenvio',
            constraint=models.UniqueConstraint(fields=('campana', 'cliente', 'programado_para'), name='uniq_campana_cliente_programado'),
        ),
    ]
