# Generated by Django 4.2.11 on 2026-01-30 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_cliente_marketing_opt_in_campanatemplate_campana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericJobConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('callable_path', models.CharField(help_text='Ruta dotted del callable o nombre registrado en app.jobs.scheduler_registry.', max_length=255)),
                ('callable_kwargs', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('paused', models.BooleanField(default=False)),
                ('schedule_type', models.CharField(choices=[('MANUAL', 'Manual'), ('DAILY', 'Diario'), ('INTERVAL', 'Intervalo'), ('CRON', 'Cron')], default='MANUAL', max_length=20)),
                ('daily_time', models.TimeField(blank=True, null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=120)),
                ('max_instances', models.PositiveIntegerField(default=1)),
                ('coalesce', models.BooleanField(default=True)),
                ('misfire_grace_seconds', models.PositiveIntegerField(default=60)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('SUCCESS', 'Exitoso'), ('ERROR', 'Error'), ('CANCELED', 'Cancelado')], max_length=20, null=True)),
                ('last_message', models.TextField(blank=True)),
                ('last_duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chained_job', models.ForeignKey(blank=True, help_text='Job a ejecutar automáticamente cuando este finaliza en SUCCESS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chained_dependents', to='app.genericjobconfig')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job programado',
                'verbose_name_plural': 'Jobs programados',
                'db_table': 'generic_job_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('SUCCESS', 'Exitoso'), ('ERROR', 'Error'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('message', models.TextField(blank=True)),
                ('backend', models.CharField(blank=True, max_length=30)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'async_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericJobRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, default='generic', max_length=50)),
                ('source_identifier', models.CharField(blank=True, db_index=True, max_length=150)),
                ('triggered_by', models.CharField(default='scheduler', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('SUCCESS', 'Exitoso'), ('ERROR', 'Error'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('run_identifier', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='app.genericjobconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de job',
                'verbose_name_plural': 'Ejecuciones de jobs',
                'db_table': 'generic_job_run_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='gjoblog_status_idx'), models.Index(fields=['started_at'], name='gjoblog_started_idx'), models.Index(fields=['job_type'], name='gjoblog_job_type_idx'), models.Index(fields=['source_identifier'], name='gjoblog_source_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='genericjobconfig',
            index=models.Index(fields=['enabled', 'paused', 'schedule_type'], name='gjobcfg_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='genericjobconfig',
            index=models.Index(fields=['last_run_at'], name='gjobcfg_last_run_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['status', 'job_type'], name='asyncjob_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['created_at'], name='asyncjob_created_idx'),
        ),
    ]
