# Generated by Django 4.2.11 on 2026-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_genericjobconfig_asyncjob_genericjobrunlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='delivery_status',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='delivery_timestamp_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='locked_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='process_after_ms',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='processed_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='queue_status',
            field=models.CharField(choices=[('pending', 'pendiente'), ('processing', 'procesando'), ('processed', 'procesado'), ('queued', 'en cola'), ('sent', 'enviado'), ('failed', 'fallido')], db_index=True, default='processed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['direccion', 'queue_status'], name='msg_queue_dir_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['queue_status', 'process_after_ms'], name='msg_queue_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(condition=models.Q(('direccion', 'in'), ('wa_message_id__isnull', False)), fields=('wa_message_id',), name='uniq_inbound_wa_message_id'),
        ),
    ]
