# Generated by Django 4.2.11 on 2026-01-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mensaje_attempts_mensaje_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WabaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('phone_id', models.CharField(max_length=50)),
                ('access_token', models.TextField()),
                ('verify_token', models.CharField(blank=True, max_length=255)),
                ('api_base', models.CharField(default='https://graph.facebook.com', max_length=255)),
                ('api_version', models.CharField(default='v22.0', max_length=20)),
                ('business_id', models.CharField(blank=True, max_length=50)),
                ('waba_id', models.CharField(blank=True, max_length=50)),
                ('webhook_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waba_config',
            },
        ),
        migrations.AddConstraint(
            model_name='wabaconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='uniq_active_waba_config'),
        ),
    ]
