# Generated by Django 4.2.11 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_wabaconfig_wabaconfig_uniq_active_waba_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="wabaconfig",
            name="interactive_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
