# Generated by Django 6.0.1 on 2026-01-31

import app.models.fields
from django.db import migrations, models


def set_default_main_menu(apps, schema_editor):
    Menu = apps.get_model("app", "Menu")
    if not Menu.objects.filter(is_main=True).exists():
        Menu.objects.filter(id="0").update(is_main=True)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_wabaconfig_interactive_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="flow_validation",
            field=app.models.fields.LenientJSONField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_main_menu, migrations.RunPython.noop),
    ]
