# Generated by Django 6.0.1 on 2026-01-31

import app.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_menu_flow_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="flow_json",
            field=app.models.fields.LenientJSONField(blank=True, null=True),
        ),
    ]
